swagger: "2.0"
info:
  title: Swagger Petstore
  version: 1.0.2
schemes:
  - http
paths:
  "/pet/{petId}":
    get:
      summary: Find a pet by ID
      description: Returns a single pet
      operationId: getPetById
      produces:
        - application/json; charset=utf-8
      parameters:
        - name: petId
          in: path
          required: true
          type: integer
          # format: int32
          x-example: 99999
      responses:
        "200":
          description: successful operation
          schema:
            "$ref": "#/definitions/Pet"
    post:
      summary: Update a pet by ID
      description: ""
      operationId: updatePet
      consumes:
        - application/json
      produces:
        - application/json; charset=utf-8
      parameters:
        - name: petId
          in: path
          required: true
          type: integer
          # format: int32
          x-example: 99999
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
                example: pochi
      responses:
        "200":
          description: successful operation
          schema:
            "$ref": "#/definitions/Pet"
definitions:
  Pet:
    type: object
    required:
      - name
      - photoUrls
    properties:
      id:
        type: integer
        # format: int32
        example: 99999
      name:
        type: string
        example: doggie
      photoUrls:
        type: array
        items:
          type: string
          example: http://example.com
      status:
        type: string
        enum:
          - available
          - pending
          - sold
        example: sold
